server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/madrasti
    username: postgres
    password: simoQB24188
  sql:
    init:
      mode: never

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info,health,metrics,loggers
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    metrics:
      enabled: true
    loggers:
      enabled: true
